version: '3.8'

services:
  mongodb:
    image: mongo:8
    container_name: local-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_DATABASE: stone-budget
    restart: unless-stopped

volumes:
  mongo-data:
